version: '3.9'

volumes:
  db_data:

services:
  menu_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: >
      sh -c "uvicorn menu_app.main:app --host 0.0.0.0 --reload"

  db:
    image: postgres:15.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5433:5433'
    expose:
      - '5433'
    command: -p 5433

  redis:
    image: redis:latest
