version: '3.9'

volumes:
  db_data_test:

networks:
  test_network:

services:
  menu_app_test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME_TEST}
      - DB_HOST=${DB_HOST_TEST}
      - DB_PORT=${DB_PORT_TEST}
      - REDIS=${REDIS_TEST}
    ports:
      - '8001:8000'
    depends_on:
      - db_test
      - redis_test
    networks:
      - test_network
    entrypoint: >
      sh -c "pytest tests/endpoints_tests.py -vv"

  db_test:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data_test:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
    ports:
      - '5434:5434'
    expose:
      - '5434'
    command: -p 5434
    networks:
      - test_network

  redis_test:
    image: redis:latest
    networks:
      - test_network
