version: '3.9'

volumes:
  db_data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done &&
        uvicorn menu_app.main:app --reload --workers 1 --host 0.0.0.0
      "
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:15.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env