version: '3.9'

volumes:
  db_data_test:

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "pytest tests -vv"

  db:
    image: postgres:15.1-alpine
    volumes:
      - db_data_test:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_NAME} -U ${POSTGRES_USER}"]
#      interval: 1s
#      timeout: 10s
#      retries: 100